"""Creating Initial Tables

Revision ID: 390373fdfa3c
Revises:
Create Date: 2020-10-12 11:52:09.035148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "390373fdfa3c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kronos_gateway",
        sa.Column("hid", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("uid", sa.Text(), nullable=False),
        sa.Column("osName", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("softwareName", sa.Text(), nullable=False),
        sa.Column("softwareVersion", sa.Text(), nullable=False),
        sa.Column("sdkVersion", sa.Text(), nullable=False),
        sa.Column("discoveredAt", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("hid"),
    )
    op.create_index(
        op.f("ix_kronos_gateway_hid"), "kronos_gateway", ["hid"], unique=False
    )
    op.create_table(
        "kronos_device",
        sa.Column("hid", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("uid", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("gatewayHid", sa.Text(), nullable=False),
        sa.Column("softwareName", sa.Text(), nullable=False),
        sa.Column("softwareVersion", sa.Text(), nullable=False),
        sa.Column("discoveredAt", sa.Integer(), nullable=False),
        sa.Column("lastPingedAt", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["gatewayHid"],
            ["kronos_gateway.hid"],
        ),
        sa.PrimaryKeyConstraint("hid"),
    )
    op.create_index(
        op.f("ix_kronos_device_hid"), "kronos_device", ["hid"], unique=False
    )
    op.create_table(
        "feeding_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column("device_hid", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_hid"],
            ["kronos_device.hid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feeding_schedule",
        sa.Column("device_hid", sa.Text(), nullable=False),
        sa.Column("time", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_hid"],
            ["kronos_device.hid"],
        ),
        sa.PrimaryKeyConstraint("device_hid", "time"),
    )
    op.create_table(
        "kronos_device_sensors",
        sa.Column("device_hid", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column("voltage", sa.Float(), nullable=False),
        sa.Column("usb_power", sa.Boolean(), nullable=False),
        sa.Column("charging", sa.Boolean(), nullable=False),
        sa.Column("ir", sa.Boolean(), nullable=False),
        sa.Column("rssi", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_hid"],
            ["kronos_device.hid"],
        ),
        sa.PrimaryKeyConstraint("device_hid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kronos_device_sensors")
    op.drop_table("feeding_schedule")
    op.drop_table("feeding_event")
    op.drop_index(op.f("ix_kronos_device_hid"), table_name="kronos_device")
    op.drop_table("kronos_device")
    op.drop_index(op.f("ix_kronos_gateway_hid"), table_name="kronos_gateway")
    op.drop_table("kronos_gateway")
    # ### end Alembic commands ###
