"""Store meal portion

Revision ID: 593d4ecb0616
Revises: a8a348a8ceae
Create Date: 2020-12-30 14:11:19.603756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "593d4ecb0616"
down_revision = "a8a348a8ceae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    connection.execute("pragma foreign_keys=OFF")
    with op.batch_alter_table("feeding_schedules", schema=None) as batch_op:
        batch_op.add_column(sa.Column("portion", sa.Float(), nullable=True))
    connection.execute("update feeding_schedules set portion = 0.0625")
    with op.batch_alter_table("feeding_schedules", schema=None) as batch_op:
        batch_op.alter_column("portion", nullable=False)
    connection.execute("pragma foreign_keys=ON")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    connection.execute("pragma foreign_keys=OFF")
    with op.batch_alter_table("feeding_schedules", schema=None) as batch_op:
        batch_op.drop_column("portion")
    connection.execute("pragma foreign_keys=ON")
    # ### end Alembic commands ###
