"""Add pets and their schedules

Revision ID: 8d04dcb08c5e
Revises: aa7ff9ab1a81
Create Date: 2020-11-15 14:38:06.917962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8d04dcb08c5e"
down_revision = "aa7ff9ab1a81"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Integer(), nullable=False),
        sa.Column("image", sa.Text(), nullable=True),
        sa.Column("animal_type", sa.Text(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("birthday", sa.Integer(), nullable=False),
        sa.Column("activity_level", sa.Integer(), nullable=False),
        sa.Column("device_hid", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_hid"],
            ["kronos_device.hid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pet_feed_schedule",
        sa.Column("pet_id", sa.Text(), nullable=False),
        sa.Column("time", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pet_id"],
            ["pets.id"],
        ),
        sa.PrimaryKeyConstraint("pet_id", "time"),
    )
    op.drop_table("feeding_schedule")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feeding_schedule",
        sa.Column("device_hid", sa.TEXT(), nullable=False),
        sa.Column("time", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_hid"],
            ["kronos_device.hid"],
        ),
        sa.PrimaryKeyConstraint("device_hid", "time"),
    )
    op.drop_table("pet_feed_schedule")
    op.drop_table("pets")
    # ### end Alembic commands ###
