"""Making 'pour' and 'full' nullable for old firmware

Revision ID: a7507af3b6bd
Revises: e62259a99df0
Create Date: 2020-10-28 19:37:25.600367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a7507af3b6bd"
down_revision = "e62259a99df0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed_event", schema=None) as batch_op:
        batch_op.alter_column(
            "full",
            existing_type=sa.INTEGER(),
            nullable=True,
            existing_server_default=sa.text("'0'"),
        )
        batch_op.alter_column(
            "pour",
            existing_type=sa.INTEGER(),
            nullable=True,
            existing_server_default=sa.text("'0'"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed_event", schema=None) as batch_op:
        batch_op.alter_column(
            "pour",
            existing_type=sa.INTEGER(),
            nullable=False,
            existing_server_default=sa.text("'0'"),
        )
        batch_op.alter_column(
            "full",
            existing_type=sa.INTEGER(),
            nullable=False,
            existing_server_default=sa.text("'0'"),
        )

    # ### end Alembic commands ###
