"""Add feed schedule for pets

Revision ID: a8a348a8ceae
Revises: 107a06aaf34c
Create Date: 2020-12-28 15:31:05.760265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a348a8ceae'
down_revision = '107a06aaf34c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeding_schedules',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Text(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.drop_table('pet_feed_schedule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_feed_schedule',
    sa.Column('pet_id', sa.TEXT(), nullable=False),
    sa.Column('time', sa.INTEGER(), nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), nullable=False),
    sa.CheckConstraint('enabled IN (0, 1)'),
    sa.CheckConstraint('enabled IN (0, 1)'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('pet_id', 'time')
    )
    op.drop_table('feeding_schedules')
    # ### end Alembic commands ###
