"""Add hopped level references and recipe table

Revision ID: bfe421f787d4
Revises: 8d04dcb08c5e
Create Date: 2020-11-21 13:23:12.180651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe421f787d4'
down_revision = '8d04dcb08c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    connection.execute('pragma foreign_keys=OFF')
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('g_per_tbsp', sa.Integer(), nullable=False),
    sa.Column('tbsp_per_feeding', sa.Integer(), nullable=False),
    sa.Column('budget_tbsp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hopper_references',
    sa.Column('device_hid', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_hid'], ['kronos_device.hid'], ),
    sa.PrimaryKeyConstraint('device_hid', 'timestamp')
    )
    with op.batch_alter_table('kronos_device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currentRecipe', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('recipes', 'recipes', ['currentRecipe'], ['id'])
    connection.execute('pragma foreign_keys=ON')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    connection.execute('pragma foreign_keys=OFF')
    with op.batch_alter_table('kronos_device', schema=None) as batch_op:
        batch_op.drop_constraint('recipes', type_='foreignkey')
        batch_op.drop_column('currentRecipe')

    op.drop_table('hopper_references')
    op.drop_table('recipes')
    connection.execute('pragma foreign_keys=ON')
    # ### end Alembic commands ###
