"""Add apiKey for feeder authentication

Revision ID: ffdfb147fffc
Revises: a7507af3b6bd
Create Date: 2020-11-01 23:44:15.128609

"""
from alembic import op
from feeder.util.feeder import generate_api_key
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffdfb147fffc'
down_revision = 'a7507af3b6bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    connection.execute('pragma foreign_keys=OFF')
    with op.batch_alter_table('kronos_gateway', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apiKey', sa.Text(), nullable=True))
    for gateway in connection.execute('select hid from kronos_gateway'):
        apiKey = generate_api_key()
        connection.execute("update kronos_gateway set apiKey = '%s' where hid = '%s'" % (apiKey, gateway[0]))
    with op.batch_alter_table('kronos_gateway', schema=None) as batch_op:
        batch_op.alter_column('apiKey', nullable=False)
    connection.execute('pragma foreign_keys=ON')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    connection.execute('pragma foreign_keys=OFF')
    with op.batch_alter_table('kronos_gateway', schema=None) as batch_op:
        batch_op.drop_column('apiKey')
    connection.execute('pragma foreign_keys=ON')

    # ### end Alembic commands ###
